# Keycloak configuration
keycloak.realm=carton-plast
keycloak.auth-server-url=https://auth-test.carton-plast.com
keycloak.ssl-required=external
keycloak.resource=carton-plast-backend
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true
# Logging Configuration
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-message=always
# Jpa Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# DataBase Configuration MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/cartonplast-dev
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDB103Dialect
# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration
spring.flyway.schemas=cartonplast-dev
