keycloak.realm=keycloak-test
keycloak.auth-server-url=https://keycloack.crsoft.org/auth
keycloak.ssl-required=external
keycloak.resource=keycloak-test-backend
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true