keycloak.realm=keycloak-master
keycloak.auth-server-url=https://keycloack.crsoft.org/auth
keycloak.ssl-required=external
keycloak.resource=keycloak-master-backend
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true