keycloak.realm=carton-plast
keycloak.auth-server-url=https://auth-test.carton-plast.com
keycloak.ssl-required=external
keycloak.resource=carton-plast-backend
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true