keycloak.realm=carton-plast
keycloak.auth-server-url=https://auth-test.carton-plast.com
keycloak.ssl-required=external
keycloak.resource=carton-plast-backend
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true

spring.datasource.url=jdbc:mariadb://167.114.46.131:3306/carton_plast_test
spring.datasource.username=crsoft
spring.datasource.password=CRsoft1^*.

spring.jpa.hibernate.ddl-auto=create-drop