spring.profiles.active=local
spring.main.allow-circular-references=true

# Open Api Configuration
app.version=v1.0.0
app.title=Docs Carton Plast API
app.description=Documentacion generada usando OPEN API
app.apiTermsOfServiceUrl=https:Certif//www.crsoft.org/terms
app.apiLicense=Apache 2.0
app.apiLicenseUrl=https://www.crsoft.org/license