/*==============================================================*/
/* Table: CATHOM                                                */
/*==============================================================*/
CREATE TABLE CATHOM
(
    ID_CATHOM_CODE    INT        NOT NULL AUTO_INCREMENT,
    CATHOM_PERCENT    INT        NOT NULL,
    CATHOM_HP_CODE    VARCHAR(2) NOT NULL,
    CATHOM_VALID_FROM TIMESTAMP,
    CATHOM_VALID_TO   TIMESTAMP  NULL,
    CATHOM_CREATED_BY VARCHAR(16),
    CATHOM_UPDATED_BY VARCHAR(16),
    CATHOM_CREATED_AT TIMESTAMP,
    CATHOM_UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID_CATHOM_CODE)
);

ALTER TABLE CATHOM
    COMMENT 'HOMOPOLIMERO';

/*==============================================================*/
/* Index: CAIHOM_HP_CODE                                        */
/*==============================================================*/
CREATE INDEX CAIHOM_HP_CODE ON CATHOM (CATHOM_HP_CODE);


/*==============================================================*/
/* Import: CATHOM Catalogos homopolimeros                       */
/*==============================================================*/
INSERT INTO CATHOM (CATHOM_PERCENT, CATHOM_HP_CODE, CATHOM_VALID_FROM, CATHOM_VALID_TO, CATHOM_CREATED_BY, CATHOM_UPDATED_BY, CATHOM_CREATED_AT, CATHOM_UPDATED_AT) VALUES (20, 'V', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATHOM (CATHOM_PERCENT, CATHOM_HP_CODE, CATHOM_VALID_FROM, CATHOM_VALID_TO, CATHOM_CREATED_BY, CATHOM_UPDATED_BY, CATHOM_CREATED_AT, CATHOM_UPDATED_AT) VALUES (30, 'T', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATHOM (CATHOM_PERCENT, CATHOM_HP_CODE, CATHOM_VALID_FROM, CATHOM_VALID_TO, CATHOM_CREATED_BY, CATHOM_UPDATED_BY, CATHOM_CREATED_AT, CATHOM_UPDATED_AT) VALUES (40, 'Q', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATHOM (CATHOM_PERCENT, CATHOM_HP_CODE, CATHOM_VALID_FROM, CATHOM_VALID_TO, CATHOM_CREATED_BY, CATHOM_UPDATED_BY, CATHOM_CREATED_AT, CATHOM_UPDATED_AT) VALUES (50, 'C', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATHOM (CATHOM_PERCENT, CATHOM_HP_CODE, CATHOM_VALID_FROM, CATHOM_VALID_TO, CATHOM_CREATED_BY, CATHOM_UPDATED_BY, CATHOM_CREATED_AT, CATHOM_UPDATED_AT) VALUES (60, 'H', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATHOM (CATHOM_PERCENT, CATHOM_HP_CODE, CATHOM_VALID_FROM, CATHOM_VALID_TO, CATHOM_CREATED_BY, CATHOM_UPDATED_BY, CATHOM_CREATED_AT, CATHOM_UPDATED_AT) VALUES (70, 'S', NULL, NULL, NULL, NULL, NULL, NULL);

