/*==============================================================*/
/* Table: CATCAT_CLI                                            */
/*==============================================================*/
CREATE TABLE CATCAT_CLI
(
    ID_CATCAT_CLI_CODE   INT NOT NULL AUTO_INCREMENT,
    CATCAT_CLI_NAME      VARCHAR(32) NOT NULL,
    CATCAT_CLI_VALID_FROM TIMESTAMP,
    CATCAT_CLI_VALID_TO  TIMESTAMP NULL,
    CATCAT_CLI_CREATED_BY VARCHAR(16),
    CATCAT_CLI_UPDATED_BY VARCHAR(16),
    CATCAT_CLI_CREATED_AT TIMESTAMP,
    CATCAT_CLI_UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID_CATCAT_CLI_CODE)
);

ALTER TABLE CATCAT_CLI COMMENT 'CATEGORIA CLIENTE';

/*==============================================================*/
/* Table: CATCLI                                                */
/*==============================================================*/
CREATE TABLE CATCLI
(
    ID_CATCLI_CODE       INT NOT NULL AUTO_INCREMENT,
    XID_CATCAT_CLI_CODE  INT,
    CATCLI_CODE          VARCHAR(16) NOT NULL,
    CATCLI_NAME          VARCHAR(64) NOT NULL,
    CATCLI_IMAGE_URL     VARCHAR(128),
    CATCLI_IMAGE_NAME    VARCHAR(128),
    CATCLI_VALID_FROM    TIMESTAMP,
    CATCLI_VALID_TO      TIMESTAMP NULL,
    CATCLI_CREATED_BY    VARCHAR(16),
    CATCLI_UPDATED_BY    VARCHAR(16),
    CATCLI_CREATED_AT    TIMESTAMP,
    CATCLI_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CATCLI_CODE)
);

ALTER TABLE CATCLI COMMENT 'CLIENTE';

/*==============================================================*/
/* Index: CAICLI_CODE                                           */
/*==============================================================*/
CREATE UNIQUE INDEX CAICLI_CODE ON CATCLI(CATCLI_CODE);

ALTER TABLE CATCLI ADD CONSTRAINT XID_CATCLI_CODE_XID_CATCAT_CLI_CODE FOREIGN KEY (XID_CATCAT_CLI_CODE)
    REFERENCES CATCAT_CLI (ID_CATCAT_CLI_CODE) ON DELETE RESTRICT;

/*==============================================================*/
/* Import: CATCLI Catalogo de clientes                          */
/*==============================================================*/
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('PTCV', NULL, 'AGRICOLA PITACAVA', 'clients/PTCV.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('ANRS', NULL, 'AGRO NATURAL RESOURCE', 'clients/ANRS.jpg', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('JALM', NULL, 'ALMEIDA JENNY', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('AMC', NULL, 'AMC', 'clients/AMC.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('APCP', NULL, 'APC-PR', 'clients/APCP.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('ACNT', NULL, 'ARCA', 'clients/ACNT.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('BLVG', NULL, 'BILVIGO', 'clients/BLVG.jpg', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('BOPP', NULL, 'BOPP DEL ECUADOR', 'clients/BOPP.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('CMNC', NULL, 'CAMANICA', 'clients/CMNC.jpg', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('TCBC', NULL, 'CBC', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('CKIN', NULL, 'CHOCK INDUSTRIES', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('CNLS', NULL, 'CONELSA', 'clients/CNLS.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('CRUT', NULL, 'CORRUCART', 'clients/CRUT.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('DYCU', NULL, 'D&C', 'clients/DYCU.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('EFLD', NULL, 'ECUAFIELDS', 'clients/EFLD.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('ECLF', NULL, 'ECUALIFES', 'clients/ECLF.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('ECMF', NULL, 'ECUAMARFRU', 'clients/ECMF.jpg', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('EMPC', NULL, 'EMPACRECI', 'clients/EMPC.jpg', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('XPLS', NULL, 'EXPALSA', 'clients/XPLS.jpg', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('FVYE', NULL, 'FAVAYE', 'clients/FVYE.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('FEVI', NULL, 'FERNANDO VILLA', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('FLPE', NULL, 'FLP', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('GOTF', NULL, 'GOTIFOODS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('GDPR', NULL, 'GUADAPRODUCTS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('HLOU', NULL, 'HENLOU - D&C', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('IVSL', NULL, 'INVERSOL', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('JALV', NULL, 'JAIME ALVARADO', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('JGRY', NULL, 'JOURDAN GRAY', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('JNGR', NULL, 'JUANAS GARDEN', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('MTRR', NULL, 'MARCELO TORRES', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('MMNT', NULL, 'MARYLIN MONTENEGRO', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('MATR', NULL, 'MATRIFLEXO', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('MNGA', NULL, 'MINGA', 'clients/MNGA.jpg', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('MDFE', NULL, 'MyD', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('NRSA', NULL, 'NIRSA', 'clients/NRSA.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('OMRA', NULL, 'OMARSA', 'clients/OMRA.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('OPIT', NULL, 'ORGANPIT', 'clients/OPIT.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('PCLR', NULL, 'PICALER - D&C', 'clients/PCLR.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('PMFR', NULL, 'PIMANFRUIT', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('PFSH', NULL, 'PITAFRESH ECUADOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('PITA', NULL, 'PITAVIT', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('PRGM', NULL, 'PRIGOURMET', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('PRCS', NULL, 'PIORICOST', 'clients/PRCS.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('PRTR', NULL, 'PROAGROTORRES', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('PRMC', NULL, 'PROMARISCO', 'clients/PRMC.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('RPLR', NULL, 'REINA PALORA', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('RSGS', NULL, 'RESGASA', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('RVAL', NULL, 'RIVAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('SPRS', NULL, 'SANTA PRISCILA', 'clients/SPRS.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('SNGA', NULL, 'SONGA', 'clients/SNGA.png', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('TDSY', NULL, 'TRADSYCOM', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('MULT', NULL, 'VARIOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('MTGR', NULL, 'MONTGAR', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('DPDS', NULL, 'DISPRODUCSA', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('MSTR', NULL, 'MUESTRAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('DSTR', NULL, 'DISTRINA', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('MFRT', NULL, 'MIRAFRUITS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('HYFR', NULL, 'HONEY FRUITS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCLI (CATCLI_CODE, XID_CATCAT_CLI_CODE, CATCLI_NAME, CATCLI_IMAGE_NAME, CATCLI_VALID_FROM, CATCLI_VALID_TO, CATCLI_CREATED_BY, CATCLI_UPDATED_BY, CATCLI_CREATED_AT, CATCLI_UPDATED_AT) VALUES ('AOVS', NULL, 'ABAD OVERSEAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
