/*==============================================================*/
/* Table: CATCTIPPRO                                            */
/*==============================================================*/
CREATE TABLE CATCTIPPRO
(
    ID_CATCTIPPRO_CODE   INT NOT NULL AUTO_INCREMENT,
    CATCTIPPRO_NAME      VARCHAR(32) NOT NULL,
    CATCTIPPRO_CODE      VARCHAR(8),
    CATCTIPPRO_VALID_FROM TIMESTAMP,
    CATCTIPPRO_VALID_TO  TIMESTAMP NULL,
    CATCTIPPRO_CREATED_BY VARCHAR(16),
    CATCTIPPRO_UPDATED_BY VARCHAR(16),
    CATCTIPPRO_CREATED_AT TIMESTAMP,
    CATCTIPPRO_UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID_CATCTIPPRO_CODE)
);

ALTER TABLE CATCTIPPRO COMMENT 'TIPO DE PROYECTO';

/*==============================================================*/
/* Table: CATCTAL                                               */
/*==============================================================*/
CREATE TABLE CATCTAL
(
    ID_CATCTAL_CODE      INT NOT NULL AUTO_INCREMENT,
    CATCTAL_PERCENT      INT NOT NULL,
    CATCTAL_LP_CODE      VARCHAR(4) NOT NULL,
    CATCTAL_VALID_FROM   TIMESTAMP,
    CATCTAL_VALID_TO     TIMESTAMP NULL,
    CATCTAL_CREATED_BY   VARCHAR(16),
    CATCTAL_UPDATED_BY   VARCHAR(16),
    CATCTAL_CREATED_AT   TIMESTAMP,
    CATCTAL_UPDATED_AT   TIMESTAMP,
    PRIMARY KEY (ID_CATCTAL_CODE)
);

ALTER TABLE CATCTAL COMMENT 'PORCENTAJE TALCO';

/*==============================================================*/
/* Table: CATCCACO3                                             */
/*==============================================================*/
CREATE TABLE CATCCACO3
(
    ID_CATCCACO3_CODE    INT NOT NULL AUTO_INCREMENT,
    CATCCACO3_PERCENT    INT NOT NULL,
    CATCCACO3_AP_CODE    VARCHAR(4) NOT NULL,
    CATCCACO3_VALID_FROM TIMESTAMP,
    CATCCACO3_VALID_TO   TIMESTAMP NULL,
    CATCCACO3_CREATED_BY VARCHAR(16),
    CATCCACO3_UPDATED_BY VARCHAR(16),
    CATCCACO3_CREATED_AT TIMESTAMP,
    CATCCACO3_UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID_CATCCACO3_CODE)
);

ALTER TABLE CATCCACO3 COMMENT 'PORCENTAJE DE CARBONATO DE CALCIO';

/*==============================================================*/
/* Table: CATCYPREFIJ                                           */
/*==============================================================*/
CREATE TABLE CATCYPREFIJ
(
    ID_CATCYPREFIJ_CODE  INT NOT NULL AUTO_INCREMENT,
    CATCYPREFIJ_NAME     VARCHAR(128) NOT NULL,
    CATCYPREFIJ_VALID_FROM TIMESTAMP,
    CATCYPREFIJ_VALID_TO TIMESTAMP NULL,
    CATCYPREFIJ_CREATED_BY VARCHAR(16),
    CATCYPREFIJ_UPDATED_BY VARCHAR(16),
    CATCYPREFIJ_CREATED_AT TIMESTAMP,
    CATCYPREFIJ_UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID_CATCYPREFIJ_CODE)
);

ALTER TABLE CATCYPREFIJ COMMENT 'CATALOGO DE Y PREFIJO';

/*==============================================================*/
/* Table: CATPROY                                               */
/*==============================================================*/
CREATE TABLE CATPROY
(
    ID_CATPROY_CODE      INT NOT NULL AUTO_INCREMENT,
    XID_CATCLI_CODE      VARCHAR(16),
    XID_CATHOM_CODE      INT NOT NULL,
    XID_CATCOL_CODE      VARCHAR(4),
    XID_CATCIR_CODE      INT,
    XID_CATCTAL_CODE     INT,
    XID_CATCCACO3_CODE   INT,
    XID_CATPRODTRO_CODE  INT,
    XID_CATCTIPPRO_CODE  INT,
    XID_CATCYPREFIJ_CODE INT,
    CATPROY_NAME         VARCHAR(128) NOT NULL,
    CATPROY_CODEGEN      VARCHAR(128) NOT NULL,
    CATPROY_GSM          INT NOT NULL,
    CATPROY_AYD_PROCESS  BOOL NOT NULL,
    CATPROY_IS_STRUCTURAL BOOL NOT NULL,
    CATPROY_HAS_CROWN    BOOL NOT NULL,
    CATPROY_LEAF_NAME    VARCHAR(64),
    CATPROY_REFERENCE_TAG VARCHAR(128),
    CATPROY_HAS_LOGO     BOOL NOT NULL,
    CATPROY_QUANTITY_X_PACKAGE INT,
    CATPROY_VALID_FROM   TIMESTAMP,
    CATPROY_VALID_TO     TIMESTAMP NULL,
    CATPROY_CREATED_BY   VARCHAR(16),
    CATPROY_UPDATED_BY   VARCHAR(16),
    CATPROY_CREATED_AT   TIMESTAMP,
    CATPROY_UPDATED_AT   TIMESTAMP,
    PRIMARY KEY (ID_CATPROY_CODE)
);

ALTER TABLE CATPROY COMMENT 'PROYECTOS';

ALTER TABLE CATPROY ADD CONSTRAINT XID_CATPROY_CODE_XID_CATCCACO3_CODE FOREIGN KEY (XID_CATCCACO3_CODE)
    REFERENCES CATCCACO3 (ID_CATCCACO3_CODE) ON DELETE RESTRICT;

ALTER TABLE CATPROY ADD CONSTRAINT XID_CATPROY_CODE_XID_CATCIR_CODE FOREIGN KEY (XID_CATCIR_CODE)
    REFERENCES CATCIR (ID_CATCIR_CODE) ON DELETE RESTRICT;

ALTER TABLE CATPROY ADD CONSTRAINT XID_CATPROY_CODE_XID_CATCLI_CODE FOREIGN KEY (XID_CATCLI_CODE)
    REFERENCES CATCLI (ID_CATCLI_CODE) ON DELETE RESTRICT;

ALTER TABLE CATPROY ADD CONSTRAINT XID_CATPROY_CODE_XID_CATCOL_CODE FOREIGN KEY (XID_CATCOL_CODE)
    REFERENCES CATCOL (ID_CATCOL_CODE) ON DELETE RESTRICT;

ALTER TABLE CATPROY ADD CONSTRAINT XID_CATPROY_CODE_XID_CATCTAL_CODE FOREIGN KEY (XID_CATCTAL_CODE)
    REFERENCES CATCTAL (ID_CATCTAL_CODE) ON DELETE RESTRICT;

ALTER TABLE CATPROY ADD CONSTRAINT XID_CATPROY_CODE_XID_CATCTIPPRO_CODE FOREIGN KEY (XID_CATCTIPPRO_CODE)
    REFERENCES CATCTIPPRO (ID_CATCTIPPRO_CODE) ON DELETE RESTRICT;

ALTER TABLE CATPROY ADD CONSTRAINT XID_CATPROY_CODE_XID_CATCYPREFIJ_CODE FOREIGN KEY (XID_CATCYPREFIJ_CODE)
    REFERENCES CATCYPREFIJ (ID_CATCYPREFIJ_CODE) ON DELETE RESTRICT;

ALTER TABLE CATPROY ADD CONSTRAINT XID_CATPROY_CODE_XID_CATHOM_CODE FOREIGN KEY (XID_CATHOM_CODE)
    REFERENCES CATHOM (ID_CATHOM_CODE) ON DELETE RESTRICT;

ALTER TABLE CATPROY ADD CONSTRAINT XID_CATPROY_CODE_XID_CATPRODTRO_CODE FOREIGN KEY (XID_CATPRODTRO_CODE)
    REFERENCES CATPRODTRO (ID_CATPRODTRO_CODE) ON DELETE RESTRICT;
