/*==============================================================*/
/* Table: CBTPER                                                */
/*==============================================================*/
CREATE TABLE CBTPER
(
    ID_CBTPER_CODE       INT NOT NULL AUTO_INCREMENT,
    CBTMEN_CODE          INT,
    CBTPER_ROLE          VARCHAR(32) NOT NULL,
    CBTPER_CREATE        BOOLEAN,
    CBTPER_READ          BOOLEAN,
    CBTPER_UPDATE        BOOLEAN,
    CBTPER_DELETE        BOOLEAN,
    CBTPER_VALID_FROM    TIMESTAMP NOT NULL,
    CBTPER_VALID_TO      TIMESTAMP,
    CBTPER_CREATED_BY    VARCHAR(16),
    CBTPER_UPDATED_BY    VARCHAR(16),
    CBTPER_CREATED_AT    TIMESTAMP NOT NULL,
    CBTPER_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CBTPER_CODE)
);

ALTER TABLE CBTPER ADD CONSTRAINT XID_CBTPER_CODE_XID_CBTMEN_CODE FOREIGN KEY (CBTMEN_CODE)
    REFERENCES CBTMEN (CBTMEN_CODE) ON DELETE RESTRICT ON UPDATE RESTRICT;