/*==============================================================*/
/* Table: CDTLOC                                                */
/*==============================================================*/
CREATE TABLE CDTLOC
(
    ID_CDTLOC_CODE       INT NOT NULL AUTO_INCREMENT,
    CDTLOC_LOCATION      VARCHAR(16) NOT NULL,
    CDTLOC_DESCRIPTION   VARCHAR(64) NOT NULL,
    CDTLOC_VALID_FROM    TIMESTAMP,
    CDTLOC_VALID_TO      TIMESTAMP NULL,
    CDTLOC_CREATED_BY    VARCHAR(16),
    CDTLOC_UPDATED_BY    VARCHAR(16),
    CDTLOC_CREATED_AT    TIMESTAMP,
    CDTLOC_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CDTLOC_CODE)
);

ALTER TABLE CDTLOC COMMENT 'UBICACION';

/*==============================================================*/
/* Table: CDTDOC                                                */
/*==============================================================*/
CREATE TABLE CDTDOC
(
    ID_CDTDOC_CODE       INT NOT NULL AUTO_INCREMENT,
    CDTDOC_NAME          VARCHAR(16) NOT NULL,
    CDTDOC_DESCRIPTION   VARCHAR(128),
    CDTDOC_VALID_FROM    TIMESTAMP,
    CDTDOC_VALID_TO      TIMESTAMP NULL,
    CDTDOC_CREATED_BY    VARCHAR(16),
    CDTDOC_UPDATED_BY    VARCHAR(16),
    CDTDOC_CREATED_AT    TIMESTAMP,
    CDTDOC_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CDTDOC_CODE)
);

ALTER TABLE CDTDOC COMMENT 'TIPO DOCUMENTO';

/*==============================================================*/
/* Table: CDTCELL                                               */
/*==============================================================*/
CREATE TABLE CDTCELL
(
    ID_CDTCELL_CODE      INT NOT NULL AUTO_INCREMENT,
    XID_CDTCAT_ID        INT,
    XID_CDTLOC_CODE      INT,
    XID_CDTDOC_CODE      INT,
    CDTCELL_LOTE         VARCHAR(16) NOT NULL,
    CDTCELL_AMOUNT       INT,
    CDTCELL_BALANCE      INT,
    CDTCELL_COAT         INT,
    CDTCELL_PALLETS      INT,
    CDTCELL_WEIGHT       INT,
    CDTCELL_DATE         TIMESTAMP NOT NULL,
    CDTCELL_OBSERVATION  VARCHAR(128),
    CDTCELL_VALID_FROM   TIMESTAMP,
    CDTCELL_VALID_TO     TIMESTAMP NULL,
    CDTCELL_CREATED_BY   VARCHAR(16),
    CDTCELL_UPDATED_BY   VARCHAR(16),
    CDTCELL_CREATED_AT   TIMESTAMP,
    CDTCELL_UPDATED_AT   TIMESTAMP,
    PRIMARY KEY (ID_CDTCELL_CODE)
);

ALTER TABLE CDTCELL COMMENT 'BODEGA';

ALTER TABLE CDTCELL ADD CONSTRAINT XID_CDTCELL_CODE_XID_CDTCAT_CODE FOREIGN KEY (XID_CDTCAT_ID)
    REFERENCES CDTCAT (ID_CDTCAT_CODE) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CDTCELL ADD CONSTRAINT XID_CDTCELL_CODE_XID_CDTLOC_CODE FOREIGN KEY (XID_CDTLOC_CODE)
    REFERENCES CDTLOC (ID_CDTLOC_CODE) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CDTCELL ADD CONSTRAINT XID_CDTCELL_CODE_XID_CDTDOC_CODE FOREIGN KEY (XID_CDTDOC_CODE)
    REFERENCES CDTDOC (ID_CDTDOC_CODE) ON DELETE RESTRICT ON UPDATE RESTRICT;

INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-01', 'Percha 01', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-02', 'Percha 02', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-03', 'Percha 03', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-04', 'Percha 04', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-05', 'Percha 05', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-06', 'Percha 06', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-07', 'Percha 07', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-08', 'Percha 08', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-09', 'Percha 09', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-10', 'Percha 10', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-11', 'Percha 11', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-12', 'Percha 12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-13', 'Percha 13', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-14', 'Percha 14', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-15', 'Percha 15', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-16', 'Percha 16', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-17', 'Percha 17', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-18', 'Percha 18', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-19', 'Percha 19', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-20', 'Percha 20', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-21', 'Percha 21', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-22', 'Percha 22', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-23', 'Percha 23', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-24', 'Percha 24', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-25', 'Percha 25', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-26', 'Percha 26', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-27', 'Percha 27', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-28', 'Percha 28', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-29', 'Percha 29', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-30', 'Percha 30', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-31', 'Percha 31', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-32', 'Percha 32', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('P-33', 'Percha 33', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-A', 'Zona A', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-B', 'Zona B', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-C', 'Zona C', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-D', 'Zona D', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-E', 'Zona E', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-F', 'Zona F', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-V', 'Zona Vehicular', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-I', 'Zona Interior', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-01', 'Zona 01', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-02', 'Zona 02', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-03', 'Zona 03', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-04', 'Zona 04', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-05', 'Zona 05', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('Z-GEN', 'Zona General', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTLOC (CDTLOC_LOCATION, CDTLOC_DESCRIPTION, CDTLOC_VALID_FROM, CDTLOC_VALID_TO, CDTLOC_CREATED_BY, CDTLOC_UPDATED_BY, CDTLOC_CREATED_AT, CDTLOC_UPDATED_AT) VALUES ('ANUL', 'ANULADO', NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO CDTDOC (CDTDOC_NAME, CDTDOC_DESCRIPTION, CDTDOC_VALID_FROM, CDTDOC_VALID_TO, CDTDOC_CREATED_BY, CDTDOC_UPDATED_BY, CDTDOC_CREATED_AT, CDTDOC_UPDATED_AT) VALUES ('CIB', 'INGRESO DE MATERIALES', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTDOC (CDTDOC_NAME, CDTDOC_DESCRIPTION, CDTDOC_VALID_FROM, CDTDOC_VALID_TO, CDTDOC_CREATED_BY, CDTDOC_UPDATED_BY, CDTDOC_CREATED_AT, CDTDOC_UPDATED_AT) VALUES ('CEB', 'EGRESO DE MATERIALES', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTDOC (CDTDOC_NAME, CDTDOC_DESCRIPTION, CDTDOC_VALID_FROM, CDTDOC_VALID_TO, CDTDOC_CREATED_BY, CDTDOC_UPDATED_BY, CDTDOC_CREATED_AT, CDTDOC_UPDATED_AT) VALUES ('MOV', 'MOVIMIENTO INTERNO', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CDTDOC (CDTDOC_NAME, CDTDOC_DESCRIPTION, CDTDOC_VALID_FROM, CDTDOC_VALID_TO, CDTDOC_CREATED_BY, CDTDOC_UPDATED_BY, CDTDOC_CREATED_AT, CDTDOC_UPDATED_AT) VALUES ('TM3', 'TRASLADO DE MATERIALES', NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO CDTCELL (XID_CDTCAT_ID, XID_CDTLOC_CODE, XID_CDTDOC_CODE, CDTCELL_LOTE, CDTCELL_AMOUNT, CDTCELL_BALANCE, CDTCELL_COAT, CDTCELL_PALLETS, CDTCELL_WEIGHT, CDTCELL_DATE, CDTCELL_OBSERVATION, CDTCELL_VALID_FROM, CDTCELL_VALID_TO, CDTCELL_CREATED_BY, CDTCELL_UPDATED_BY, CDTCELL_CREATED_AT, CDTCELL_UPDATED_AT) VALUES (60, 37, 2, 'M240221', 0, 0, -32, 0, -800, '2022-04-28 00:00:00', 'TRASLADO DE BODEGA CP ALA PLANTA /', NULL, NULL, NULL, NULL, NULL, NULL);
