/*==============================================================*/
/* Table: CATCIRDOC                                             */
/*==============================================================*/
CREATE TABLE CATCIRDOC
(
    ID_CATCIRDOC_CODE       INT NOT NULL AUTO_INCREMENT,
    XID_CATCIR_CODE         INT NOT NULL,
    CATCIRDOC_VERSION       INT NOT NULL,
    CATCIRDOC_NAME          VARCHAR(256) NOT NULL,
    CATCIRDOC_VERSION_DATE  TIMESTAMP NOT NULL,
    CATCIRDOC_VALID_FROM    TIMESTAMP,
    CATCIRDOC_VALID_TO      TIMESTAMP NULL,
    CATCIRDOC_CREATED_BY    VARCHAR(16),
    CATCIRDOC_UPDATED_BY    VARCHAR(16),
    CATCIRDOC_CREATED_AT    TIMESTAMP,
    CATCIRDOC_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CATCIRDOC_CODE)
);

ALTER TABLE CATCIRDOC COMMENT 'DOCUMENTOS CIREL';

ALTER TABLE CATCIRDOC ADD CONSTRAINT XID_CATCIRDOC_CODE_XID_CATCIR_CODE FOREIGN KEY (XID_CATCIR_CODE)
    REFERENCES CATCIR (ID_CATCIR_CODE) ON DELETE RESTRICT;

/*==============================================================*/
/* Import: CATCIRDOC Catalogo de documentos de cireles          */
/*==============================================================*/
INSERT INTO CATCIRDOC (ID_CATCIRDOC_CODE, XID_CATCIR_CODE, CATCIRDOC_VERSION, CATCIRDOC_NAME, CATCIRDOC_VERSION_DATE, CATCIRDOC_VALID_FROM, CATCIRDOC_VALID_TO, CATCIRDOC_CREATED_BY, CATCIRDOC_UPDATED_BY, CATCIRDOC_CREATED_AT, CATCIRDOC_UPDATED_AT) VALUES (1, 107, 1, 'cireles/P079-X1-WGR-210112V01.pdf', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

/*==============================================================*/
/* Table: CATTRODOC                                             */
/*==============================================================*/
CREATE TABLE CATTRODOC
(
    ID_CATTRODOC_CODE       INT NOT NULL AUTO_INCREMENT,
    XID_CATTRO_CODE         INT NOT NULL,
    CATTRODOC_VERSION       INT NOT NULL,
    CATTRODOC_NAME          VARCHAR(256) NOT NULL,
    CATTRODOC_VERSION_DATE  TIMESTAMP NOT NULL,
    CATTRODOC_VALID_FROM    TIMESTAMP,
    CATTRODOC_VALID_TO      TIMESTAMP NULL,
    CATTRODOC_CREATED_BY    VARCHAR(16),
    CATTRODOC_UPDATED_BY    VARCHAR(16),
    CATTRODOC_CREATED_AT    TIMESTAMP,
    CATTRODOC_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CATTRODOC_CODE)
);

ALTER TABLE CATTRODOC COMMENT 'DOCUMENTOS TROQUEL';

ALTER TABLE CATTRODOC ADD CONSTRAINT XID_CATTRODOC_CODE_XID_CATTRO_CODE FOREIGN KEY (XID_CATTRO_CODE)
    REFERENCES CATTRO (ID_CATTRO_CODE) ON DELETE RESTRICT;

/*==============================================================*/
/* Import: CATTRODOC Catalogo de documentos de troqueles        */
/*==============================================================*/
INSERT INTO CATTRODOC (ID_CATTRODOC_CODE, XID_CATTRO_CODE, CATTRODOC_VERSION, CATTRODOC_NAME, CATTRODOC_VERSION_DATE, CATTRODOC_VALID_FROM, CATTRODOC_VALID_TO, CATTRODOC_CREATED_BY, CATTRODOC_UPDATED_BY, CATTRODOC_CREATED_AT, CATTRODOC_UPDATED_AT) VALUES (1, 50, 1, 'troqueles/T106-X1M1-210217V01.pdf', NULL, NULL, NULL, NULL, NULL, NULL, NULL);