/*==============================================================*/
/* Table: CETMIX                                                */
/*==============================================================*/
CREATE TABLE CETMIX
(
    ID_CETMIX_CODE          INT NOT NULL AUTO_INCREMENT,
    XID_COTORD_CODE         INT NOT NULL,
    CETMIX_DIE              INT NOT NULL,
    CETMIX_PREPARE          INT NOT NULL,
    CETMIX_PRE_MIXTURE      INT NOT NULL,
    CETMIX_OBSERVATION      VARCHAR(256),
    CETMIX_NUMBER           INT NOT NULL,
    CETMIX_DOCUMENT_BY      VARCHAR(32) NOT NULL,
    CETMIX_DOCUMENT_TO      VARCHAR(32) NOT NULL,
    CETMIX_MIXTURE          VARCHAR(32) NOT NULL,
    CETMIX_DATE             TIMESTAMP NOT NULL ,
    CETMIX_TOTAL            DOUBLE NOT NULL,
    CETMIX_TOTAL_REAL       DOUBLE NOT NULL,
    CETMIX_VALID_FROM       TIMESTAMP,
    CETMIX_VALID_TO         TIMESTAMP NULL,
    CETMIX_CREATED_BY       VARCHAR(16),
    CETMIX_UPDATED_BY       VARCHAR(16),
    CETMIX_CREATED_AT       TIMESTAMP,
    CETMIX_UPDATED_AT       TIMESTAMP,
    PRIMARY KEY (ID_CETMIX_CODE)
);

ALTER TABLE CETMIX COMMENT 'MEZCLA';

/*==============================================================*/
/* Table: CETMIX_DET                                            */
/*==============================================================*/
CREATE TABLE CETMIX_DET
(
    ID_CETMIX_DET_CODE          INT NOT NULL AUTO_INCREMENT,
    XID_CETMIX_CODE             INT NOT NULL,
    XID_CDTCAT_CODE             INT NOT NULL,
    CETMIX_DET_PERCENT          DOUBLE NOT NULL,
    CETMIX_DET_STOP             DOUBLE NOT NULL,
    CETMIX_DET_TOTAL            DOUBLE NOT NULL,
    CETMIX_DET_VALID_FROM       TIMESTAMP,
    CETMIX_DET_VALID_TO         TIMESTAMP NULL,
    CETMIX_DET_CREATED_BY       VARCHAR(16),
    CETMIX_DET_UPDATED_BY       VARCHAR(16),
    CETMIX_DET_CREATED_AT       TIMESTAMP,
    CETMIX_DET_UPDATED_AT       TIMESTAMP,
    PRIMARY KEY (ID_CETMIX_DET_CODE)
);

ALTER TABLE CETMIX_DET COMMENT 'MEZCLA DETALLE';

ALTER TABLE CETMIX ADD CONSTRAINT XID_CETMIX_CODE_XID_COTORD_CODE FOREIGN KEY (XID_COTORD_CODE)
    REFERENCES COTORD (ID_COTORD_CODE) ON DELETE RESTRICT;

ALTER TABLE CETMIX_DET ADD CONSTRAINT XID_CETMIX_DET_CODE_XID_CETMIX_CODE FOREIGN KEY (XID_CETMIX_CODE)
    REFERENCES CETMIX (ID_CETMIX_CODE) ON DELETE RESTRICT;

ALTER TABLE CETMIX_DET ADD CONSTRAINT XID_CETMIX_DET_CODE_XID_CDTCAT_CODE FOREIGN KEY (XID_CDTCAT_CODE)
    REFERENCES CDTCAT (ID_CDTCAT_CODE) ON DELETE RESTRICT;

INSERT INTO `cartonplast-dev`.CETMIX (ID_CETMIX_CODE, XID_COTORD_CODE, CETMIX_DIE, CETMIX_PREPARE, CETMIX_PRE_MIXTURE, CETMIX_OBSERVATION, CETMIX_NUMBER, CETMIX_DOCUMENT_BY, CETMIX_DOCUMENT_TO, CETMIX_MIXTURE, CETMIX_DATE, CETMIX_TOTAL, CETMIX_TOTAL_REAL, CETMIX_VALID_FROM, CETMIX_VALID_TO, CETMIX_CREATED_BY, CETMIX_UPDATED_BY, CETMIX_CREATED_AT, CETMIX_UPDATED_AT) VALUES (1, 946, 14, 20, 200, 'TEST', 1, 'Carton Plast Admin', 'Responsables Mezcla', 'QB2', '2022-07-07 22:09:15', 4000, 1759.6000000000001, '2022-07-07 22:09:16', null, 'cadmin', 'cadmin', '2022-07-07 22:09:16', '2022-07-07 22:09:16');

INSERT INTO `cartonplast-dev`.CETMIX_DET (ID_CETMIX_DET_CODE, XID_CETMIX_CODE, XID_CDTCAT_CODE, CETMIX_DET_PERCENT, CETMIX_DET_STOP, CETMIX_DET_TOTAL, CETMIX_DET_VALID_FROM, CETMIX_DET_VALID_TO, CETMIX_DET_CREATED_BY, CETMIX_DET_UPDATED_BY, CETMIX_DET_CREATED_AT, CETMIX_DET_UPDATED_AT) VALUES (1, 1, 19, 27.5, 55, 1100, '2022-07-07 22:09:16', null, 'cadmin', 'cadmin', '2022-07-07 22:09:16', '2022-07-07 22:09:16');
INSERT INTO `cartonplast-dev`.CETMIX_DET (ID_CETMIX_DET_CODE, XID_CETMIX_CODE, XID_CDTCAT_CODE, CETMIX_DET_PERCENT, CETMIX_DET_STOP, CETMIX_DET_TOTAL, CETMIX_DET_VALID_FROM, CETMIX_DET_VALID_TO, CETMIX_DET_CREATED_BY, CETMIX_DET_UPDATED_BY, CETMIX_DET_CREATED_AT, CETMIX_DET_UPDATED_AT) VALUES (2, 1, 28, 41, 82, 1640, '2022-07-07 22:09:16', null, 'cadmin', 'cadmin', '2022-07-07 22:09:16', '2022-07-07 22:09:16');
INSERT INTO `cartonplast-dev`.CETMIX_DET (ID_CETMIX_DET_CODE, XID_CETMIX_CODE, XID_CDTCAT_CODE, CETMIX_DET_PERCENT, CETMIX_DET_STOP, CETMIX_DET_TOTAL, CETMIX_DET_VALID_FROM, CETMIX_DET_VALID_TO, CETMIX_DET_CREATED_BY, CETMIX_DET_UPDATED_BY, CETMIX_DET_CREATED_AT, CETMIX_DET_UPDATED_AT) VALUES (3, 1, 73, 1, 2, 40, '2022-07-07 22:09:16', null, 'cadmin', 'cadmin', '2022-07-07 22:09:16', '2022-07-07 22:09:16');
INSERT INTO `cartonplast-dev`.CETMIX_DET (ID_CETMIX_DET_CODE, XID_CETMIX_CODE, XID_CDTCAT_CODE, CETMIX_DET_PERCENT, CETMIX_DET_STOP, CETMIX_DET_TOTAL, CETMIX_DET_VALID_FROM, CETMIX_DET_VALID_TO, CETMIX_DET_CREATED_BY, CETMIX_DET_UPDATED_BY, CETMIX_DET_CREATED_AT, CETMIX_DET_UPDATED_AT) VALUES (4, 1, 61, 0.5, 1, 20, '2022-07-07 22:09:16', null, 'cadmin', 'cadmin', '2022-07-07 22:09:16', '2022-07-07 22:09:16');
INSERT INTO `cartonplast-dev`.CETMIX_DET (ID_CETMIX_DET_CODE, XID_CETMIX_CODE, XID_CDTCAT_CODE, CETMIX_DET_PERCENT, CETMIX_DET_STOP, CETMIX_DET_TOTAL, CETMIX_DET_VALID_FROM, CETMIX_DET_VALID_TO, CETMIX_DET_CREATED_BY, CETMIX_DET_UPDATED_BY, CETMIX_DET_CREATED_AT, CETMIX_DET_UPDATED_AT) VALUES (5, 1, 132, 30, 60, 1200, '2022-07-07 22:09:16', null, 'cadmin', 'cadmin', '2022-07-07 22:09:16', '2022-07-07 22:09:16');
