/*==============================================================*/
/* Table: CETMIX                                                */
/*==============================================================*/
CREATE TABLE CETMIX
(
    ID_CETMIX_CODE          INT NOT NULL AUTO_INCREMENT,
    XID_COTORD_CODE         INT NOT NULL,
    CETMIX_NUMBER           INT NOT NULL,
    CETMIX_DOCUMENT_TO      VARCHAR(32) NOT NULL,
    CETMIX_DOCUMENT_BY      VARCHAR(32) NOT NULL,
    CETMIX_DATE             TIMESTAMP NOT NULL ,
    CETMIX_PREPARE          INT NOT NULL,
    CETMIX_TOTAL            DOUBLE NOT NULL,
    CETMIX_OBSERVATION      VARCHAR(256),
    CETMIX_VALID_FROM       TIMESTAMP,
    CETMIX_VALID_TO         TIMESTAMP NULL,
    CETMIX_CREATED_BY       VARCHAR(16),
    CETMIX_UPDATED_BY       VARCHAR(16),
    CETMIX_CREATED_AT       TIMESTAMP,
    CETMIX_UPDATED_AT       TIMESTAMP,
    PRIMARY KEY (ID_CETMIX_CODE)
);

ALTER TABLE CETMIX COMMENT 'MEZCLA';

/*==============================================================*/
/* Table: CETMIX_DET                                            */
/*==============================================================*/
CREATE TABLE CETMIX_DET
(
    ID_CETMIX_DET_CODE          INT NOT NULL AUTO_INCREMENT,
    XID_CETMIX_CODE             INT NOT NULL,
    XID_CDTCAT_CODE             INT NOT NULL,
    CETMIX_DET_PERCENT          DOUBLE NOT NULL,
    CETMIX_DET_STOP             DOUBLE NOT NULL,
    CETMIX_DET_TOTAL            DOUBLE NOT NULL,
    CETMIX_DET_VALID_FROM       TIMESTAMP,
    CETMIX_DET_VALID_TO         TIMESTAMP NULL,
    CETMIX_DET_CREATED_BY       VARCHAR(16),
    CETMIX_DET_UPDATED_BY       VARCHAR(16),
    CETMIX_DET_CREATED_AT       TIMESTAMP,
    CETMIX_DET_UPDATED_AT       TIMESTAMP,
    PRIMARY KEY (ID_CETMIX_DET_CODE)
);

ALTER TABLE CETMIX_DET COMMENT 'MEZCLA DETALLE';

ALTER TABLE CETMIX ADD CONSTRAINT XID_CETMIX_CODE_XID_COTORD_CODE FOREIGN KEY (XID_COTORD_CODE)
    REFERENCES COTORD (ID_COTORD_CODE) ON DELETE RESTRICT;

ALTER TABLE CETMIX_DET ADD CONSTRAINT XID_CETMIX_DET_CODE_XID_CETMIX_CODE FOREIGN KEY (XID_CETMIX_CODE)
    REFERENCES CETMIX (ID_CETMIX_CODE) ON DELETE RESTRICT;

ALTER TABLE CETMIX_DET ADD CONSTRAINT XID_CETMIX_DET_CODE_XID_CDTCAT_CODE FOREIGN KEY (XID_CDTCAT_CODE)
    REFERENCES CDTCAT (ID_CDTCAT_CODE) ON DELETE RESTRICT;