ALTER TABLE CATCLI
    ADD COLUMN IF NOT EXISTS CATCLI_IMAGE_URL VARCHAR(128) NULL
        AFTER CATCLI_NAME;
ALTER TABLE CATCLI
    ADD COLUMN IF NOT EXISTS CATCLI_IMAGE_NAME VARCHAR(128) NULL
        AFTER CATCLI_IMAGE_URL;