/*==============================================================*/
/* Table: CATPRI                                                */
/*==============================================================*/
CREATE TABLE CATPRI
(
    ID_CATPRI_CODE       VARCHAR(4) NOT NULL,
    CATPRI_NAME          VARCHAR(32) NOT NULL,
    CATPRI_TYPE          VARCHAR(4) NOT NULL,
    CATPRI_ICON          VARCHAR(32) NOT NULL,
    CATPRI_COLOR         VARCHAR(32),
    CATPRI_INDEX         INT NOT NULL,
    CATPRI_VALID_FROM    TIMESTAMP,
    CATPRI_VALID_TO      TIMESTAMP NULL,
    CATPRI_CREATED_BY    VARCHAR(16),
    CATPRI_UPDATED_BY    VARCHAR(16),
    CATPRI_CREATED_AT    TIMESTAMP,
    CATPRI_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CATPRI_CODE)
);

ALTER TABLE CATPRI COMMENT 'CATALOGO PRIORIDAD';

/*==============================================================*/
/* Import: CATPRI Catalogo de prioridad                         */
/*==============================================================*/
INSERT INTO CATPRI (ID_CATPRI_CODE, CATPRI_NAME, CATPRI_TYPE, CATPRI_ICON, CATPRI_COLOR, CATPRI_INDEX, CATPRI_VALID_FROM, CATPRI_VALID_TO, CATPRI_CREATED_BY, CATPRI_UPDATED_BY, CATPRI_CREATED_AT, CATPRI_UPDATED_AT) VALUES ('BAP', 'BAJA', 'P', 'pi-angle-down', NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATPRI (ID_CATPRI_CODE, CATPRI_NAME, CATPRI_TYPE, CATPRI_ICON, CATPRI_COLOR, CATPRI_INDEX, CATPRI_VALID_FROM, CATPRI_VALID_TO, CATPRI_CREATED_BY, CATPRI_UPDATED_BY, CATPRI_CREATED_AT, CATPRI_UPDATED_AT) VALUES ('MEP', 'MEDIA', 'P', 'pi-bars', 'p-button-success', 3, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATPRI (ID_CATPRI_CODE, CATPRI_NAME, CATPRI_TYPE, CATPRI_ICON, CATPRI_COLOR, CATPRI_INDEX, CATPRI_VALID_FROM, CATPRI_VALID_TO, CATPRI_CREATED_BY, CATPRI_UPDATED_BY, CATPRI_CREATED_AT, CATPRI_UPDATED_AT) VALUES ('ALP', 'ALTA', 'P', 'pi-angle-up', 'p-button-warning ', 2, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATPRI (ID_CATPRI_CODE, CATPRI_NAME, CATPRI_TYPE, CATPRI_ICON, CATPRI_COLOR, CATPRI_INDEX, CATPRI_VALID_FROM, CATPRI_VALID_TO, CATPRI_CREATED_BY, CATPRI_UPDATED_BY, CATPRI_CREATED_AT, CATPRI_UPDATED_AT) VALUES ('CRP', 'CRITICA', 'P', 'pi-angle-double-up', 'p-button-danger', 1, NULL, NULL, NULL, NULL, NULL, NULL);


/*==============================================================*/
/* Table: COTORD                                                */
/*==============================================================*/
CREATE TABLE COTORD
(
    ID_COTORD_CODE       INT NOT NULL AUTO_INCREMENT,
    XID_CATPRI_CODE      VARCHAR(4) NOT NULL,
    XID_COT_ID_COTORD_CODE INT,
    XID_CATPROY_CODE     INT NOT NULL,
    XID_CATCLI_CODE      INT NOT NULL,
    XID_CATSTATUS_CODE   VARCHAR(4) NOT NULL,
    COTORD_CODE          VARCHAR(8) NOT NULL,
    COTORD_PRODUCT_CODE  VARCHAR(128) NOT NULL,
    COTORD_NAME          VARCHAR(128) NOT NULL,
    COTORD_QUANTITY      INT NOT NULL,
    COTORD_ORDERED_AT    TIMESTAMP NOT NULL,
    COTORD_LOTE          VARCHAR(16),
    COTORD_ESTIMATED_DELIVERED_AT TIMESTAMP,
    COTORD_CLIENT_ORDER_CODE VARCHAR(64),
    COTORD_OBSERVATION   VARCHAR(256),
    COTORD_COMPLETED_AT  TIMESTAMP,
    COTORD_CANCELED_AT   TIMESTAMP,
    COTORD_PRODUCTION_STARTED_AT TIMESTAMP,
    COTORD_CANCELLATION_REASON VARCHAR(256),
    COTORD_LAST_MODIFICATION_AT TIMESTAMP NOT NULL,
    COTORD_VALID_FROM    TIMESTAMP,
    COTORD_VALID_TO      TIMESTAMP NULL,
    COTORD_CREATED_BY    VARCHAR(10),
    COTORD_UPDATED_BY    VARCHAR(10),
    COTORD_CREATED_AT    TIMESTAMP,
    COTORD_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_COTORD_CODE)
);

ALTER TABLE COTORD COMMENT 'PEDIDOS';

ALTER TABLE COTORD ADD CONSTRAINT XID_COTORD_CODE_XID_CATCLI_CODE FOREIGN KEY (XID_CATCLI_CODE)
    REFERENCES CATCLI (ID_CATCLI_CODE) ON DELETE RESTRICT;

ALTER TABLE COTORD ADD CONSTRAINT XID_COTORD_CODE_XID_CATPRI_CODE FOREIGN KEY (XID_CATPRI_CODE)
    REFERENCES CATPRI (ID_CATPRI_CODE) ON DELETE RESTRICT;

ALTER TABLE COTORD ADD CONSTRAINT XID_COTORD_CODE_XID_CATPROY_CODE FOREIGN KEY (XID_CATPROY_CODE)
    REFERENCES CATPROY (ID_CATPROY_CODE) ON DELETE RESTRICT;

ALTER TABLE COTORD ADD CONSTRAINT XID_COTORD_CODE_XID_CATSTATUS_CODE FOREIGN KEY (XID_CATSTATUS_CODE)
    REFERENCES CATSTATUS (ID_CATSTATUS_CODE) ON DELETE RESTRICT;

ALTER TABLE COTORD ADD CONSTRAINT XID_COTORD_CODE_XID_COTORD_CODE FOREIGN KEY (XID_COT_ID_COTORD_CODE)
    REFERENCES COTORD (ID_COTORD_CODE) ON DELETE RESTRICT;