/*==============================================================*/
/* Table: CFTTURN                                               */
/*==============================================================*/
CREATE TABLE CFTTURN
(
    ID_CFTTURN_CODE      INT NOT NULL AUTO_INCREMENT,
    CFTTURN_NAME         VARCHAR(32) NOT NULL,
    CFTTURN_START_TIME   TIME NOT NULL,
    CFTTURN_END_TIME     TIME NOT NULL,
    CFTTURN_IS_ACTIVE    BOOL NOT NULL,
    CFTTURN_VALID_FROM   TIMESTAMP,
    CFTTURN_VALID_TO     TIMESTAMP NULL,
    CFTTURN_CREATED_BY   VARCHAR(16),
    CFTTURN_UPDATED_BY   VARCHAR(16),
    CFTTURN_CREATED_AT   TIMESTAMP,
    CFTTURN_UPDATED_AT   TIMESTAMP,
    PRIMARY KEY (ID_CFTTURN_CODE)
);

ALTER TABLE CFTTURN COMMENT 'TURNOS';

/*==============================================================*/
/* Import: CFTTURN Catalogos turnos                             */
/*==============================================================*/
INSERT INTO CFTTURN (ID_CFTTURN_CODE, CFTTURN_NAME, CFTTURN_START_TIME, CFTTURN_END_TIME, CFTTURN_IS_ACTIVE, CFTTURN_VALID_FROM, CFTTURN_VALID_TO, CFTTURN_CREATED_BY, CFTTURN_UPDATED_BY, CFTTURN_CREATED_AT, CFTTURN_UPDATED_AT) VALUES (1, 'Turno 1', '00:00:00', '07:59:59', TRUE, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CFTTURN (ID_CFTTURN_CODE, CFTTURN_NAME, CFTTURN_START_TIME, CFTTURN_END_TIME, CFTTURN_IS_ACTIVE, CFTTURN_VALID_FROM, CFTTURN_VALID_TO, CFTTURN_CREATED_BY, CFTTURN_UPDATED_BY, CFTTURN_CREATED_AT, CFTTURN_UPDATED_AT) VALUES (2, 'Turno 2', '08:00:00', '15:59:59', TRUE, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CFTTURN (ID_CFTTURN_CODE, CFTTURN_NAME, CFTTURN_START_TIME, CFTTURN_END_TIME, CFTTURN_IS_ACTIVE, CFTTURN_VALID_FROM, CFTTURN_VALID_TO, CFTTURN_CREATED_BY, CFTTURN_UPDATED_BY, CFTTURN_CREATED_AT, CFTTURN_UPDATED_AT) VALUES (3, 'Turno 3', '16:00:00', '23:59:59', TRUE, NULL, NULL, NULL, NULL, NULL, NULL);

/*==============================================================*/
/* Table: CFTREQMAT                                             */
/*==============================================================*/
CREATE TABLE CFTREQMAT
(
    ID_CFTREQMAT_CODE    INT NOT NULL AUTO_INCREMENT,
    XID_CFTTURN_CODE     INT NOT NULL,
    XID_CATSTATUS_CODE   VARCHAR(4) NOT NULL,
    CFTREQMAT_NUMBER     VARCHAR(32) NOT NULL,
    CFTREQMAT_DATE       TIMESTAMP NOT NULL,
    CFTREQMAT_DOC_BY_USERNAME VARCHAR(16) NOT NULL,
    CFTREQMAT_DOC_BY     VARCHAR(128) NOT NULL,
    CFTREQMAT_VALID_FROM TIMESTAMP,
    CFTREQMAT_VALID_TO   TIMESTAMP NULL,
    CFTREQMAT_CREATED_BY VARCHAR(16),
    CFTREQMAT_UPDATED_BY VARCHAR(16),
    CFTREQMAT_CREATED_AT TIMESTAMP,
    CFTREQMAT_UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID_CFTREQMAT_CODE)
);

ALTER TABLE CFTREQMAT COMMENT 'SOLICITUD DE MATERIA PRIMA';

ALTER TABLE CFTREQMAT ADD CONSTRAINT XID_CFTREQMAT_CODE_XID_CATSTATUS_CODE FOREIGN KEY (XID_CATSTATUS_CODE)
    REFERENCES CATSTATUS (ID_CATSTATUS_CODE) ON DELETE RESTRICT;

ALTER TABLE CFTREQMAT ADD CONSTRAINT XID_CFTREQMAT_CODE_XID_CFTTURN_CODE FOREIGN KEY (XID_CFTTURN_CODE)
    REFERENCES CFTTURN (ID_CFTTURN_CODE) ON DELETE RESTRICT;

/*==============================================================*/
/* Table: CFTREQMAT_DET                                         */
/*==============================================================*/
CREATE TABLE CFTREQMAT_DET
(
    ID_CFTREQMAT_DET_CODE INT NOT NULL AUTO_INCREMENT,
    XID_CDTCAT_CODE      INT NOT NULL,
    XID_CFTREQMAT_CODE   INT NOT NULL,
    CFTREQMAT_DET_BALANCE DOUBLE,
    CFTREQMAT_DET_COAT   DOUBLE,
    CFTREQMAT_DET_PALLETS DOUBLE,
    CFTREQMAT_DET_WEIGHT DOUBLE NOT NULL,
    CFTREQMAT_DET_CONSOLIDATED DOUBLE NOT NULL,
    CFTREQMAT_DET_COAT_NUMBER INT NOT NULL,
    CFTREQMAT_DET_PALLET_NUMBER INT NOT NULL,
    CFTREQMAT_DET_OBSERVATION VARCHAR(256),
    CFTREQMAT_DET_VALID_FROM TIMESTAMP,
    CFTREQMAT_DET_VALID_TO TIMESTAMP NULL,
    CFTREQMAT_DET_CREATED_BY VARCHAR(16),
    CFTREQMAT_DET_UPDATED_BY VARCHAR(16),
    CFTREQMAT_DET_CREATED_AT TIMESTAMP,
    CFTREQMAT_DET_UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID_CFTREQMAT_DET_CODE)
);

ALTER TABLE CFTREQMAT_DET COMMENT 'DETALLE SOLICITUD DE MATERIA PRIMA';

ALTER TABLE CFTREQMAT_DET ADD CONSTRAINT XID_CFTREQMAT_DET_CODE_XID_CDTCAT_CODE FOREIGN KEY (XID_CDTCAT_CODE)
    REFERENCES CDTCAT (ID_CDTCAT_CODE) ON DELETE RESTRICT;

ALTER TABLE CFTREQMAT_DET ADD CONSTRAINT XID_CFTREQMAT_DET_CODE_XID_CFTREQMAT_CODE FOREIGN KEY (XID_CFTREQMAT_CODE)
    REFERENCES CFTREQMAT (ID_CFTREQMAT_CODE) ON DELETE RESTRICT;
