/*==============================================================*/
/* Table: CATTHI                                                */
/*==============================================================*/
CREATE TABLE CATTHI
(
    ID_CATTHI_CODE       INT NOT NULL AUTO_INCREMENT,
    CATTHI_WEIGHT        INT NOT NULL,
    CATTHI_THICKNESS     DECIMAL(4,2),
    CATTHI_USD           DECIMAL(4,2) NOT NULL,
    CATTHI_VALID_FROM    TIMESTAMP,
    CATTHI_VALID_TO      TIMESTAMP NULL,
    CATTHI_CREATED_BY    VARCHAR(16),
    CATTHI_UPDATED_BY    VARCHAR(16),
    CATTHI_CREATED_AT    TIMESTAMP,
    CATTHI_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CATTHI_CODE)
);

ALTER TABLE CATTHI COMMENT 'Espesor';

/*==============================================================*/
/* Import: CATTHI Catalogo de espesores                         */
/*==============================================================*/
INSERT INTO CATTHI (CATTHI_WEIGHT, CATTHI_THICKNESS, CATTHI_USD, CATTHI_VALID_FROM, CATTHI_VALID_TO, CATTHI_CREATED_BY, CATTHI_UPDATED_BY, CATTHI_CREATED_AT, CATTHI_UPDATED_AT) VALUES (300, 2.1, 1.05, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATTHI (CATTHI_WEIGHT, CATTHI_THICKNESS, CATTHI_USD, CATTHI_VALID_FROM, CATTHI_VALID_TO, CATTHI_CREATED_BY, CATTHI_UPDATED_BY, CATTHI_CREATED_AT, CATTHI_UPDATED_AT) VALUES (400, 2.4, 1.4, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATTHI (CATTHI_WEIGHT, CATTHI_THICKNESS, CATTHI_USD, CATTHI_VALID_FROM, CATTHI_VALID_TO, CATTHI_CREATED_BY, CATTHI_UPDATED_BY, CATTHI_CREATED_AT, CATTHI_UPDATED_AT) VALUES (500, 2.7, 1.75, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATTHI (CATTHI_WEIGHT, CATTHI_THICKNESS, CATTHI_USD, CATTHI_VALID_FROM, CATTHI_VALID_TO, CATTHI_CREATED_BY, CATTHI_UPDATED_BY, CATTHI_CREATED_AT, CATTHI_UPDATED_AT) VALUES (600, 3, 2.1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATTHI (CATTHI_WEIGHT, CATTHI_THICKNESS, CATTHI_USD, CATTHI_VALID_FROM, CATTHI_VALID_TO, CATTHI_CREATED_BY, CATTHI_UPDATED_BY, CATTHI_CREATED_AT, CATTHI_UPDATED_AT) VALUES (700, 3.3, 2.45, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATTHI (CATTHI_WEIGHT, CATTHI_THICKNESS, CATTHI_USD, CATTHI_VALID_FROM, CATTHI_VALID_TO, CATTHI_CREATED_BY, CATTHI_UPDATED_BY, CATTHI_CREATED_AT, CATTHI_UPDATED_AT) VALUES (800, 3.6, 2.8, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATTHI (CATTHI_WEIGHT, CATTHI_THICKNESS, CATTHI_USD, CATTHI_VALID_FROM, CATTHI_VALID_TO, CATTHI_CREATED_BY, CATTHI_UPDATED_BY, CATTHI_CREATED_AT, CATTHI_UPDATED_AT) VALUES (900, 3.9, 3.15, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATTHI (CATTHI_WEIGHT, CATTHI_THICKNESS, CATTHI_USD, CATTHI_VALID_FROM, CATTHI_VALID_TO, CATTHI_CREATED_BY, CATTHI_UPDATED_BY, CATTHI_CREATED_AT, CATTHI_UPDATED_AT) VALUES (1000, NULL, 3.5, NULL, NULL, NULL, NULL, NULL, NULL);