/*==============================================================*/
/* Table: CATIMP                                                */
/*==============================================================*/
CREATE TABLE CATIMP
(
    ID_CATIMP_CODE       INT NOT NULL AUTO_INCREMENT,
    CATIMP_NAME          VARCHAR(64) NOT NULL,
    CATIMP_NUM_COLORS    INT NOT NULL,
    CATIMP_DESCRIPTION   VARCHAR(64),
    CATIMP_VALID_FROM    TIMESTAMP,
    CATIMP_VALID_TO      TIMESTAMP NULL,
    CATIMP_CREATED_BY    VARCHAR(16),
    CATIMP_UPDATED_BY    VARCHAR(16),
    CATIMP_CREATED_AT    TIMESTAMP,
    CATIMP_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CATIMP_CODE)
);

ALTER TABLE CATIMP COMMENT 'IMPRESORA';

/*==============================================================*/
/* Index: CATIMP_INDEX                                          */
/*==============================================================*/
CREATE INDEX CAIIMP_NAME ON CATIMP (CATIMP_NAME);

/*==============================================================*/
/* Import: CATIMP Catalogo de impresoras                        */
/*==============================================================*/
INSERT INTO CATIMP (CATIMP_NAME, CATIMP_NUM_COLORS, CATIMP_DESCRIPTION, CATIMP_VALID_FROM, CATIMP_VALID_TO, CATIMP_CREATED_BY, CATIMP_UPDATED_BY, CATIMP_CREATED_AT, CATIMP_UPDATED_AT) VALUES ('Impresora 2 colores', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

/*==============================================================*/
/* Table: CATCIR                                                */
/*==============================================================*/
CREATE TABLE CATCIR
(
    ID_CATCIR_CODE       INT NOT NULL AUTO_INCREMENT,
    XID_CATTRO_CODE      INT,
    XID_CATCOL_CODE      VARCHAR(4),
    XID_CATIMP_CODE      INT NOT NULL,
    XID_CATCLI_CODE      VARCHAR(16) NOT NULL,
    CATCIR_PRINT         VARCHAR(8) NOT NULL,
    CATCIR_DESCRIPTION   VARCHAR(128) NOT NULL,
    CATCIR_DESCRIPTION2  VARCHAR(128),
    CATCIR_OBSERVATION   VARCHAR(128),
    CATCIR_VALID_FROM    TIMESTAMP,
    CATCIR_VALID_TO      TIMESTAMP NULL,
    CATCIR_CREATED_BY    VARCHAR(16),
    CATCIR_UPDATED_BY    VARCHAR(16),
    CATCIR_CREATED_AT    TIMESTAMP,
    CATCIR_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CATCIR_CODE)
);

ALTER TABLE CATCIR COMMENT 'CIREL';

/*==============================================================*/
/* Index: CAICIR_PRINT                                          */
/*==============================================================*/
CREATE INDEX CAICIR_PRINT ON CATCIR (CATCIR_PRINT);

ALTER TABLE CATCIR ADD CONSTRAINT XID_CATCIR_CODE_XID_CATCLI_CODE FOREIGN KEY (XID_CATCLI_CODE)
    REFERENCES CATCLI (ID_CATCLI_CODE) ON DELETE RESTRICT;

ALTER TABLE CATCIR ADD CONSTRAINT XID_CATCIR_CODE_XID_CATCOL_CODE FOREIGN KEY (XID_CATCOL_CODE)
    REFERENCES CATCOL (ID_CATCOL_CODE) ON DELETE RESTRICT;

ALTER TABLE CATCIR ADD CONSTRAINT XID_CATCIR_CODE_XID_CATIMP_CODE FOREIGN KEY (XID_CATIMP_CODE)
    REFERENCES CATIMP (ID_CATIMP_CODE) ON DELETE RESTRICT;

ALTER TABLE CATCIR ADD CONSTRAINT XID_CATCIR_CODE_XID_CATTRO_CODE FOREIGN KEY (XID_CATTRO_CODE)
    REFERENCES CATTRO (ID_CATTRO_CODE) ON DELETE RESTRICT;

/*==============================================================*/
/* Table: CATCOLTI                                              */
/*==============================================================*/
CREATE TABLE CATCOLTI
(
    ID_CATCOLTI_CODE     VARCHAR(2) NOT NULL,
    CATCOLTI_NAME        VARCHAR(32) NOT NULL,
    CATCOLTI_VALID_FROM  TIMESTAMP,
    CATCOLTI_VALID_TO    TIMESTAMP NULL,
    CATCOLTI_CREATED_BY  VARCHAR(16),
    CATCOLTI_UPDATED_BY  VARCHAR(16),
    CATCOLTI_CREATED_AT  TIMESTAMP,
    CATCOLTI_UPDATED_AT  TIMESTAMP,
    PRIMARY KEY (ID_CATCOLTI_CODE)
);

ALTER TABLE CATCOLTI COMMENT 'TIPO DE COLOR';

/*==============================================================*/
/* Import: CATCOLTI Catalogo tipo de color del cirel            */
/*==============================================================*/
INSERT INTO CATCOLTI (ID_CATCOLTI_CODE, CATCOLTI_NAME, CATCOLTI_VALID_FROM, CATCOLTI_VALID_TO, CATCOLTI_CREATED_BY, CATCOLTI_UPDATED_BY, CATCOLTI_CREATED_AT, CATCOLTI_UPDATED_AT) VALUES ('LA', 'LÁMINA', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CATCOLTI (ID_CATCOLTI_CODE, CATCOLTI_NAME, CATCOLTI_VALID_FROM, CATCOLTI_VALID_TO, CATCOLTI_CREATED_BY, CATCOLTI_UPDATED_BY, CATCOLTI_CREATED_AT, CATCOLTI_UPDATED_AT) VALUES ('CI', 'CIREL', NULL, NULL, NULL, NULL, NULL, NULL);

/*==============================================================*/
/* Table: CATCIR_COL                                            */
/*==============================================================*/
CREATE TABLE CATCIR_COL
(
    ID_CATCIR_COL_CODE   INT NOT NULL AUTO_INCREMENT,
    XID_CATCIR_CODE      INT NOT NULL,
    XID_CATCATCOL_CODE   INT NOT NULL,
    XID_CATCOLTI_CODE    VARCHAR(2) NOT NULL,
    CATCIR_COL_INDEX     INT NOT NULL,
    CATCIR_COL_VALID_FROM TIMESTAMP,
    CATCIR_COL_VALID_TO  TIMESTAMP NULL,
    CATCIR_COL_CREATED_BY VARCHAR(16),
    CATCIR_COL_UPDATED_BY VARCHAR(16),
    CATCIR_COL_CREATED_AT TIMESTAMP,
    CATCIR_COL_UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID_CATCIR_COL_CODE)
);

ALTER TABLE CATCIR_COL COMMENT 'CIREL COLOR';

ALTER TABLE CATCIR_COL ADD CONSTRAINT XID_CATCIR_COL_CODE_XID_CATCIR_CODE FOREIGN KEY (XID_CATCIR_CODE)
    REFERENCES CATCIR (ID_CATCIR_CODE) ON DELETE RESTRICT;

ALTER TABLE CATCIR_COL ADD CONSTRAINT XID_CATCIRL_COL_CODE_XID_CATCATCOL_CODE FOREIGN KEY (XID_CATCATCOL_CODE)
    REFERENCES CATCATCOL (ID_CATCATCOL_CODE) ON DELETE RESTRICT;

ALTER TABLE CATCIR_COL ADD CONSTRAINT XID_CATCIR_COL_CODE_XID_CATCOLTI_CODE FOREIGN KEY (XID_CATCOLTI_CODE)
    REFERENCES CATCOLTI (ID_CATCOLTI_CODE) ON DELETE RESTRICT;
