

/*==============================================================*/
/* Table: CBTUSE                                                */
/*==============================================================*/
CREATE TABLE CBTUSE
(
    ID_CBTUSE_CODE       VARCHAR(64) NOT NULL,
    XID_CBTPRE_CODE      INTEGER,
    XID_CBTPERSON_CODE   INTEGER NOT NULL,
    CBTUSE_USERNAME      VARCHAR(32) NOT NULL,
    CBTUSE_VALID_FROM    TIMESTAMP,
    CBTUSE_VALID_TO      TIMESTAMP NULL,
    CBTUSE_CREATED_BY    VARCHAR(16),
    CBTUSE_UPDATED_BY    VARCHAR(16),
    CBTUSE_CREATED_AT    TIMESTAMP,
    CBTUSE_UPDATED_AT    TIMESTAMP,
    PRIMARY KEY (ID_CBTUSE_CODE)
);

ALTER TABLE CBTUSE COMMENT 'USUARIO';

/*==============================================================*/
/* Index: CBIUSE_USERNAME                                       */
/*==============================================================*/
CREATE UNIQUE INDEX CBIUSE_USERNAME ON CBTUSE(CBTUSE_USERNAME);

/*==============================================================*/
/* Index: XID_CBIPRE_CODE                                       */
/*==============================================================*/
CREATE UNIQUE INDEX XID_CBIPRE_CODE ON CBTUSE(XID_CBTPRE_CODE);

ALTER TABLE CBTUSE ADD CONSTRAINT XID_CBTUSE_CODE_XID_CBTPERSON_CODE FOREIGN KEY (XID_CBTPERSON_CODE)
    REFERENCES CBTPERSON (ID_CBTPERSON_CODE) ON DELETE RESTRICT;

ALTER TABLE CBTUSE ADD CONSTRAINT XID_CBTUSE_CODE_XID_CBTPRE_CODE FOREIGN KEY (XID_CBTPRE_CODE)
    REFERENCES CBTPRE (ID_CBTPRE_CODE) ON DELETE RESTRICT;


/*==============================================================*/
/* Import: CBTUSE Catalogos usuarios                            */
/*==============================================================*/
INSERT INTO CBTUSE (ID_CBTUSE_CODE, XID_CBTPRE_CODE, XID_CBTPERSON_CODE, CBTUSE_USERNAME, CBTUSE_VALID_FROM, CBTUSE_VALID_TO, CBTUSE_CREATED_BY, CBTUSE_UPDATED_BY, CBTUSE_CREATED_AT, CBTUSE_UPDATED_AT) VALUES ('823ea6a9-9b1c-4824-b444-38b7a8bd7e8f', 3, 9999, 'cpadmin', NULL, NULL, 'cpadmin', 'cpadmin', NULL, NULL);
INSERT INTO CBTUSE (ID_CBTUSE_CODE, XID_CBTPRE_CODE, XID_CBTPERSON_CODE, CBTUSE_USERNAME, CBTUSE_VALID_FROM, CBTUSE_VALID_TO, CBTUSE_CREATED_BY, CBTUSE_UPDATED_BY, CBTUSE_CREATED_AT, CBTUSE_UPDATED_AT) VALUES ('aaa202cc-6ed3-4207-b697-a3b5cdad3551', 4, 2017, 'csupervisor', NULL, NULL, 'cpadmin', 'cpadmin', NULL, NULL);
INSERT INTO CBTUSE (ID_CBTUSE_CODE, XID_CBTPRE_CODE, XID_CBTPERSON_CODE, CBTUSE_USERNAME, CBTUSE_VALID_FROM, CBTUSE_VALID_TO, CBTUSE_CREATED_BY, CBTUSE_UPDATED_BY, CBTUSE_CREATED_AT, CBTUSE_UPDATED_AT) VALUES ('fd3c8cbc-98fa-494d-a9a6-48fc86ce3ac5', 5, 9999, 'cuser', NULL, NULL, 'cpadmin', 'cpadmin', NULL, NULL);
INSERT INTO CBTUSE (ID_CBTUSE_CODE, XID_CBTPRE_CODE, XID_CBTPERSON_CODE, CBTUSE_USERNAME, CBTUSE_VALID_FROM, CBTUSE_VALID_TO, CBTUSE_CREATED_BY, CBTUSE_UPDATED_BY, CBTUSE_CREATED_AT, CBTUSE_UPDATED_AT) VALUES ('491f122a-bd9a-48f5-bf50-3061c8faef58', 6, 9999, 'cadmin', NULL, NULL, 'cpadmin', 'cpadmin', NULL, NULL);
INSERT INTO CBTUSE (ID_CBTUSE_CODE, XID_CBTPRE_CODE, XID_CBTPERSON_CODE, CBTUSE_USERNAME, CBTUSE_VALID_FROM, CBTUSE_VALID_TO, CBTUSE_CREATED_BY, CBTUSE_UPDATED_BY, CBTUSE_CREATED_AT, CBTUSE_UPDATED_AT) VALUES ('999c37ee-a8c2-4167-a6e2-336965f16a57', 7, 9997, 'jyepez', NULL, NULL, 'cpadmin', 'cpadmin', NULL, NULL);
INSERT INTO CBTUSE (ID_CBTUSE_CODE, XID_CBTPRE_CODE, XID_CBTPERSON_CODE, CBTUSE_USERNAME, CBTUSE_VALID_FROM, CBTUSE_VALID_TO, CBTUSE_CREATED_BY, CBTUSE_UPDATED_BY, CBTUSE_CREATED_AT, CBTUSE_UPDATED_AT) VALUES ('cbfe4c0f-7a8c-4ed5-a9be-1e951549cf89', 8, 2151, 'wyela', NULL, NULL, 'cpadmin', 'cpadmin', NULL, NULL);
INSERT INTO CBTUSE (ID_CBTUSE_CODE, XID_CBTPRE_CODE, XID_CBTPERSON_CODE, CBTUSE_USERNAME, CBTUSE_VALID_FROM, CBTUSE_VALID_TO, CBTUSE_CREATED_BY, CBTUSE_UPDATED_BY, CBTUSE_CREATED_AT, CBTUSE_UPDATED_AT) VALUES ('ea206bc8-4b49-4017-abb9-6936b2cb5707', 9, 9999, 'lpillaga', NULL, NULL, 'cpadmin', 'cpadmin', NULL, NULL);
INSERT INTO CBTUSE (ID_CBTUSE_CODE, XID_CBTPRE_CODE, XID_CBTPERSON_CODE, CBTUSE_USERNAME, CBTUSE_VALID_FROM, CBTUSE_VALID_TO, CBTUSE_CREATED_BY, CBTUSE_UPDATED_BY, CBTUSE_CREATED_AT, CBTUSE_UPDATED_AT) VALUES ('7c2264ec-7312-4604-b440-2154da1cddf9', 10, 9996, 'lgrocha', NULL, NULL, 'cpadmin', 'cpadmin', NULL, NULL);
